export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const FILTER_SORT_PRODUCTS = 'FILTER_SORT_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';